services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh ./start_web.sh
    env_file:
      - ./.env
    environment:
      APP_ENV: production
    ports:
      - "8080:8080"
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kub.rule=Host(`your-domain.com`)"
      - "traefik.http.services.kub.loadbalancer.server.port=8080"
      - "traefik.http.routers.kub.tls=true"
      - "traefik.http.routers.kub.tls.certresolver=resolver"
