"""summ str

Revision ID: 196e80d177fa
Revises: aa4e751c0775
Create Date: 2025-11-15 13:27:25.387811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196e80d177fa'
down_revision = 'aa4e751c0775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('summ',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('summ',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
