"""payment

Revision ID: cc6824b964d3
Revises: 10c599942e5f
Create Date: 2025-11-09 15:34:54.360972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6824b964d3'
down_revision = '10c599942e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('payment_date', sa.String(length=8), nullable=True),
    sa.Column('receiving_date', sa.String(length=8), nullable=True),
    sa.Column('summ', sa.Integer(), nullable=True),
    sa.Column('summ_words', sa.String(length=512), nullable=True),
    sa.Column('payment_purpose', sa.String(length=1024), nullable=True),
    sa.Column('payer_name', sa.String(length=128), nullable=True),
    sa.Column('payer_code', sa.String(length=10), nullable=True),
    sa.Column('payer_bank_name', sa.String(length=512), nullable=True),
    sa.Column('payer_bank_code', sa.String(length=512), nullable=True),
    sa.Column('payer_iban', sa.String(length=512), nullable=True),
    sa.Column('recipient_name', sa.String(length=128), nullable=True),
    sa.Column('recipient_code', sa.String(length=10), nullable=True),
    sa.Column('recipient_bank_name', sa.String(length=512), nullable=True),
    sa.Column('recipient_bank_code', sa.String(length=512), nullable=True),
    sa.Column('recipient_iban', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
